// <auto-generated />
namespace Resume.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditAwareEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditAwareEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201812251115033_EditAwareEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
